// This file will be auto-generated by Supabase CLI once the schema is created.
// Run: npx supabase gen types typescript --local > src/types/database.ts
// Placeholder types to satisfy TypeScript until then.

export type Database = {
  public: {
    Tables: Record<string, never>;
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
};
